#! /bin/sh

function help {
    echo "jasmine - a few commands to help you includes the jasmine JavaScript testing library in your project";
    echo "";
    echo "    jasmine init                  - include jasmine in the project";
    echo "    jasmine create \$FunctionName  - creates ./src/FunctionName.js ./spec/FunctionNameSpec.js";
    echo "    jasmine run                   - runs tests in browser";
}

if [ $1 ] 
  then
    case "$1" in
    "init")
      curl -O http://pivotal.github.com/jasmine/downloads/jasmine-standalone-1.1.0.rc1.zip
      unzip jasmine-standalone-1.1.0.rc1.zip
      mkdir lib spec src
      mv ./jasmine-standalone-1.1.0.rc1/lib/jasmine-1.1.0.rc1 ./lib
      mv ./jasmine-standalone-1.1.0.rc1/SpecRunner.html ./SpecRunner.html
      rm -rf ./jasmine-standalone-1.1.0 ./jasmine-standalone-1.1.0.rc1 ./jasmine-standalone-1.1.0.rc1.zip
      if [ xattr ]
        then
        xattr -d -r com.apple.quarantine ./SpecRunner.html
      fi
      sed -i '' '13,19d' SpecRunner.html
    ;;
    "create")
      if [ $2 ]
        then 
          echo "function $2 () {\n\n}" > ./src/$2.js
          echo "describe('$2', function () {\n\n});" > ./spec/$2Spec.js
        else
          echo 'please add a name for the file'
      fi
    ;;
    "run")
      open ./SpecRunner.html
    ;;
    "--help")
      help;
    ;;
    *)
      help;
    ;;
    esac
  else
    help;
fi
