#! /bin/sh

function help {
    echo "jasmine - a few commands to help you includes the jasmine JavaScript testing library in your project";
    echo "command: jasmine";
    echo "    init - include jasmine in the project";
    echo "    create \$FunctionName - creates ./src/FunctionName.js ./spec/FunctionNameSpec.js";
    echo "    open - runs tests in browser";
}

if [ $1 ] 
  then
    case "$1" in
    "init")
      curl -O http://pivotal.github.com/jasmine/downloads/jasmine-standalone-1.1.0.rc1.zip
      unzip jasmine-standalone-1.1.0.rc1.zip
      mkdir lib spec src
      mv ./jasmine-standalone-1.1.0.rc1/lib/jasmine-1.1.0.rc1 ./lib/jasmine
      mv ./jasmine-standalone-1.1.0.rc1/SpecRunner.html ./SpecRunner.html
      rm -rf ./jasmine-standalone-1.1.0 ./jasmine-standalone-1.1.0.rc1 ./jasmine-standalone-1.1.0.rc1.zip
    ;;
    "create")
      echo "create $2 coming";
    ;;
    "open")
      echo "open coming";
    ;;
    "--help")
      help;
    ;;
    *)
      help;
    ;;
    esac
  else
    help;
fi

