#! /bin/sh

function help {
    echo "jazz - A simple script that makes using the Jasmine testing framework in a standalone project a little simpler."
    echo "";
    echo "    jazz init                  - include jasmine in the project";
    echo "    jazz create \$FunctionName  - creates ./src/FunctionName.js ./spec/FunctionNameSpec.js";
    echo "    jazz run                   - runs tests in browser";
}

if [ $1 ] 
  then
    case "$1" in
    "init")
      curl -O http://pivotal.github.com/jasmine/downloads/jasmine-standalone-1.1.0.rc1.zip
      unzip jasmine-standalone-1.1.0.rc1.zip
      mkdir lib spec src
      mv ./jasmine-standalone-1.1.0.rc1/lib/jasmine-1.1.0.rc1 ./lib
      mv ./jasmine-standalone-1.1.0.rc1/SpecRunner.html ./SpecRunner.html
      rm -rf ./jasmine-standalone-1.1.0 ./jasmine-standalone-1.1.0.rc1 ./jasmine-standalone-1.1.0.rc1.zip
      if [ xattr ]
        then
        xattr -d -r com.apple.quarantine ./SpecRunner.html
      fi
      sed -i '' '13,19d' SpecRunner.html
    ;;
    "create")
      if [ $2 ]
        then 
          echo "function $2 () {\n\n}" > ./src/$2.js
          echo "describe('$2', function () {\n\n});" > ./spec/$2Spec.js
	  sed -i '' "12 a\\
		<!-- $2 Source and Spec --> \\
		<script src='src/$2.js'></script> \\
		<script src='spec/$2Spec.js'></script> \\
		\\
		" SpecRunner.html
        else
          echo 'please add a name for the file'
      fi
    ;;
    "run")
      open ./SpecRunner.html
    ;;
    "--help")
      help;
    ;;
    *)
      help;
    ;;
    esac
  else
    help;
fi
